spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3300/tablegame?characterEncoding=UTF-8
      username: root
      password: JiaChenXin.123
